"""add skills to experience

Revision ID: 249787a3c334
Revises: 1abd983d415f
Create Date: 2025-06-03 09:55:07.821340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '249787a3c334'
down_revision: Union[str, None] = '1abd983d415f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_experience', sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_experience', 'skills')
    # ### end Alembic commands ###
