"""

Revision ID: 28be5d8e70db
Revises: 49a850cca923
Create Date: 2025-03-27 13:37:30.699194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28be5d8e70db'
down_revision: Union[str, None] = '49a850cca923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'attachments', ['profile_picture'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'profile_picture')
    # ### end Alembic commands ###
