"""added fields in candidate

Revision ID: 35e1f687a507
Revises: ef36260e4694
Create Date: 2025-05-20 19:51:32.815389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35e1f687a507'
down_revision: Union[str, None] = 'ef36260e4694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('personal_growth', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('candidates', sa.Column('who_am_i', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('candidates', sa.Column('success_stories', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'success_stories')
    op.drop_column('candidates', 'who_am_i')
    op.drop_column('candidates', 'personal_growth')
    # ### end Alembic commands ###
