"""llm model to user table

Revision ID: 40e20833a8bd
Revises: d9f59e415115
Create Date: 2025-07-22 22:34:05.802387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40e20833a8bd'
down_revision: Union[str, None] = 'd9f59e415115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('llm_models', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_llm_models_id'), 'llm_models', ['id'], unique=False)
    op.add_column('users', sa.Column('selected_llm_model', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'llm_models', ['selected_llm_model'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'selected_llm_model')
    op.drop_index(op.f('ix_llm_models_id'), table_name='llm_models')
    op.alter_column('llm_models', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
