"""

Revision ID: 49a850cca923
Revises: 6fbcc53648c7
Create Date: 2025-03-27 01:10:00.799653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49a850cca923'
down_revision: Union[str, None] = '6fbcc53648c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    account_type_enum = sa.Enum('candidate', 'recruiter', name='account_type_enum')
    account_type_enum.create(op.get_bind(), checkfirst=True)

    # Add the column using the enum type
    op.add_column('users', sa.Column('account_type', account_type_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'account_type')
    # ### end Alembic commands ###
