"""cascade

Revision ID: 52061d86df06
Revises: 28be5d8e70db
Create Date: 2025-04-14 12:58:25.296211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52061d86df06'
down_revision: Union[str, None] = '28be5d8e70db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('candidates_user_id_fkey', 'candidates', type_='foreignkey')
    op.create_foreign_key(None, 'candidates', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('chat_messages_chat_session_id_fkey', 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'chat_sessions', ['chat_session_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('chat_sessions_user_id_fkey', 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'chat_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('recruiters_user_id_fkey', 'recruiters', type_='foreignkey')
    op.create_foreign_key(None, 'recruiters', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('sessions_user_id_fkey', 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('temp_chat_sessions_user_id_fkey', 'temp_chat_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'temp_chat_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('vacancies_recruiter_id_fkey', 'vacancies', type_='foreignkey')
    op.create_foreign_key(None, 'vacancies', 'recruiters', ['recruiter_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancies', type_='foreignkey')
    op.create_foreign_key('vacancies_recruiter_id_fkey', 'vacancies', 'recruiters', ['recruiter_id'], ['id'])
    op.drop_constraint(None, 'temp_chat_sessions', type_='foreignkey')
    op.create_foreign_key('temp_chat_sessions_user_id_fkey', 'temp_chat_sessions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key('sessions_user_id_fkey', 'sessions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'recruiters', type_='foreignkey')
    op.create_foreign_key('recruiters_user_id_fkey', 'recruiters', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.create_foreign_key('chat_sessions_user_id_fkey', 'chat_sessions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key('chat_messages_chat_session_id_fkey', 'chat_messages', 'chat_sessions', ['chat_session_id'], ['id'])
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.create_foreign_key('candidates_user_id_fkey', 'candidates', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
