"""verification table

Revision ID: 6bbeec17a3c5
Revises: faa92431663d
Create Date: 2025-06-03 08:46:26.508716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bbeec17a3c5'
down_revision: Union[str, None] = 'faa92431663d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_experience_verification',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('work_experience_id', sa.UUID(), nullable=False),
    sa.Column('verifier_id', sa.Integer(), nullable=False),
    sa.Column('verification_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['verifier_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_experience_id'], ['work_experience.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_experience_verification_id'), 'work_experience_verification', ['id'], unique=False)
    op.create_index(op.f('ix_work_experience_verification_verifier_id'), 'work_experience_verification', ['verifier_id'], unique=False)
    op.create_index(op.f('ix_work_experience_verification_work_experience_id'), 'work_experience_verification', ['work_experience_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_experience_verification_work_experience_id'), table_name='work_experience_verification')
    op.drop_index(op.f('ix_work_experience_verification_verifier_id'), table_name='work_experience_verification')
    op.drop_index(op.f('ix_work_experience_verification_id'), table_name='work_experience_verification')
    op.drop_table('work_experience_verification')
    # ### end Alembic commands ###
