"""

Revision ID: 6fbcc53648c7
Revises: 582de5ea198b
Create Date: 2025-03-24 12:33:59.638427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6fbcc53648c7'
down_revision: Union[str, None] = '582de5ea198b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp_chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('candidates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temp_chat_sessions_id'), 'temp_chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_temp_chat_sessions_user_id'), 'temp_chat_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temp_chat_sessions_user_id'), table_name='temp_chat_sessions')
    op.drop_index(op.f('ix_temp_chat_sessions_id'), table_name='temp_chat_sessions')
    op.drop_table('temp_chat_sessions')
    # ### end Alembic commands ###
