"""recruter profile pic

Revision ID: 765e858f7301
Revises: a58a129377dc
Create Date: 2025-02-17 12:16:22.827492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '765e858f7301'
down_revision: Union[str, None] = 'a58a129377dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruiters', sa.Column('profile_picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recruiters', 'profile_picture')
    # ### end Alembic commands ###
