"""a lot of changes

Revision ID: 775bf7017229
Revises: 249787a3c334
Create Date: 2025-06-03 13:52:07.180201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '775bf7017229'
down_revision: Union[str, None] = '249787a3c334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_experience_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('work_experience_id', sa.UUID(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('duration', sa.String(), nullable=False),
    sa.Column('team_size', sa.Integer(), nullable=False),
    sa.Column('impact', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['work_experience_id'], ['work_experience.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_experience_projects_id'), 'work_experience_projects', ['id'], unique=False)
    op.create_index(op.f('ix_work_experience_projects_work_experience_id'), 'work_experience_projects', ['work_experience_id'], unique=False)
    op.add_column('work_experience', sa.Column('description', sa.String(), nullable=True))
    op.add_column('work_experience', sa.Column('key_achievements', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_experience', 'key_achievements')
    op.drop_column('work_experience', 'description')
    op.drop_index(op.f('ix_work_experience_projects_work_experience_id'), table_name='work_experience_projects')
    op.drop_index(op.f('ix_work_experience_projects_id'), table_name='work_experience_projects')
    op.drop_table('work_experience_projects')
    # ### end Alembic commands ###
