"""

Revision ID: b4b8e6e17880
Revises: f6d624bf1aeb
Create Date: 2025-02-24 15:08:53.510652

"""
from turtle import pos
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4b8e6e17880'
down_revision: Union[str, None] = 'f6d624bf1aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'address',
                    existing_type=sa.VARCHAR(),
                    type_=postgresql.JSONB(astext_type=sa.Text()),
                    postgresql_using='address::jsonb',  # Explicit cast
                    existing_nullable=True)
    op.alter_column('candidates', 'work_experience',
                    existing_type=sa.VARCHAR(),
                    type_=postgresql.JSONB(astext_type=sa.Text()),
                    postgresql_using='work_experience::jsonb',  # Explicit cast
                    existing_nullable=True)
    op.alter_column('candidates', 'education',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               postgresql_using='education::jsonb',  # Explicit cast
               existing_nullable=True)
    op.alter_column('candidates', 'skills',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               postgresql_using='skills::jsonb',  # Explicit cast
               existing_nullable=True)
    op.alter_column('candidates', 'certifications',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               postgresql_using='certifications::jsonb',  # Explicit cast
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'certifications',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
                postgresql_using='certifications::text',  # Explicit cast
               existing_nullable=True)
    op.alter_column('candidates', 'skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               postgresql_using='skills::text',  # Explicit cast
               existing_nullable=True)
    op.alter_column('candidates', 'education',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               postgresql_using='education::text',  # Explicit cast
               existing_nullable=True)
    op.alter_column('candidates', 'work_experience',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    type_=sa.VARCHAR(),
                    postgresql_using='work_experience::text',  # Explicit cast
                    existing_nullable=True)
    op.alter_column('candidates', 'address',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    type_=sa.VARCHAR(),
                    postgresql_using='address::text',  # Explicit cast
                    existing_nullable=True)
    # ### end Alembic commands ###
