"""

Revision ID: f6d624bf1aeb
Revises: a61694152470
Create Date: 2025-02-24 13:47:53.106248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6d624bf1aeb'
down_revision: Union[str, None] = 'a61694152470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('email', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('address', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('date_of_birth', sa.DateTime(), nullable=True))
    op.add_column('candidates', sa.Column('years_of_experience', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('job_title', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('work_experience', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('education', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('skills', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('certifications', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'certifications')
    op.drop_column('candidates', 'skills')
    op.drop_column('candidates', 'education')
    op.drop_column('candidates', 'work_experience')
    op.drop_column('candidates', 'job_title')
    op.drop_column('candidates', 'years_of_experience')
    op.drop_column('candidates', 'date_of_birth')
    op.drop_column('candidates', 'address')
    op.drop_column('candidates', 'phone_number')
    op.drop_column('candidates', 'email')
    # ### end Alembic commands ###
