"""Initial migration

Revision ID: f6dad7b06b47
Revises: 
Create Date: 2025-02-06 12:12:17.434472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6dad7b06b47'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcription_id'), 'transcription', ['id'], unique=False)
    op.create_index(op.f('ix_transcription_text'), 'transcription', ['text'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcription_text'), table_name='transcription')
    op.drop_index(op.f('ix_transcription_id'), table_name='transcription')
    op.drop_table('transcription')
    # ### end Alembic commands ###
