"""candiate status

Revision ID: fbce86670080
Revises: 2e08455573b3
Create Date: 2025-03-12 13:16:37.481104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbce86670080'
down_revision: Union[str, None] = '2e08455573b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('status', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'created_at')
    op.drop_column('candidates', 'status')
    # ### end Alembic commands ###
