name: Deploy Backend to EC2

# Trigger the workflow on pushes to the main branch
on:
  push:
    branches:
      - main # Or your primary branch (e.g., master)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        # Useful for cross-platform builds if needed later

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          # Use the default GITHUB_TOKEN for authentication within the same repo
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
          

      - name: Build and push Docker image
        id: build-push
        uses: docker/build-push-action@v5
        with:
          context: . # Assumes Dockerfile is in the root directory
          file: ./Dockerfile # Explicit path to your Dockerfile
          push: true
          # Ensure the image name is lowercase
          # ghcr.io/OWNER/REPO:latest
          tags: ghcr.io/${{ github.repository_owner,, }}/${{ github.event.repository.name,, }}:latest
          cache-from: type=gha # Enable build cache from GitHub Actions cache
          cache-to: type=gha,mode=max # Write build cache to GitHub Actions cache

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3 # Use a specific version tag
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # --- Deployment Script on EC2 ---

            # Variables
            # Ensure image name uses lowercase owner/repo as used in the build step
            IMAGE_NAME="ghcr.io/${{ github.repository_owner,, }}/${{ github.event.repository.name,, }}:latest"
            CONTAINER_NAME="atsBackend"
            # Define where the .env file should be placed on the EC2 instance
            # Ensure the EC2_USERNAME has write permissions here or adjust the path/permissions
            ENV_FILE_PATH="/home/${{ secrets.EC2_USERNAME }}/app.env" # Or e.g., /opt/myapp/app.env

            echo "--- Logging into GHCR on EC2 ---"
            # Use the GITHUB_TOKEN passed via secrets context for EC2 login
            # Note: GITHUB_TOKEN has limited permissions and expires. A PAT (secrets.GHCR_PAT) might be more robust for pulling.
            echo ${{ secrets.GHCR_PAT }} | sudo docker login ghcr.io -u ${{ github.actor }} --password-stdin
            # If using PAT:
            # echo ${{ secrets.GHCR_PAT }} | sudo docker login ghcr.io -u YOUR_GITHUB_USERNAME --password-stdin

            echo "--- Stopping existing container ($CONTAINER_NAME) ---"
            # Stop the container if it exists, ignore error if it doesn't
            sudo docker stop $CONTAINER_NAME || true

            echo "--- Removing existing container ($CONTAINER_NAME) ---"
            # Remove the container if it exists, ignore error if it doesn't
            sudo docker rm $CONTAINER_NAME || true

            echo "--- Pulling latest image ($IMAGE_NAME) ---"
            sudo docker pull $IMAGE_NAME

            echo "--- Creating environment file ($ENV_FILE_PATH) ---"
            # Use 'cat <<EOF' to handle multi-line secrets properly
            # Ensure the target directory exists if ENV_FILE_PATH is not in the user's home
            # sudo mkdir -p $(dirname $ENV_FILE_PATH) # Uncomment if needed
            # sudo chown ${{ secrets.EC2_USERNAME }}:${{ secrets.EC2_USERNAME }} $(dirname $ENV_FILE_PATH) # Uncomment if needed
            cat <<EOF | sudo tee $ENV_FILE_PATH > /dev/null
            ${{ secrets.ENV_FILE_CONTENT }}
            EOF
            # Optional: Secure the .env file permissions
            sudo chmod 600 $ENV_FILE_PATH
            # Ensure the user running docker can read it, or adjust ownership if needed
            # sudo chown some_user:some_group $ENV_FILE_PATH # If needed

            echo "--- Running new container ($CONTAINER_NAME) ---"
            sudo docker run -d \
              -p 8000:8000 \
              --name $CONTAINER_NAME \
              --env-file $ENV_FILE_PATH \
              $IMAGE_NAME

            echo "--- Deployment complete ---"

            # Optional: Clean up unused Docker images to save space
            echo "--- Cleaning up dangling images ---"
            sudo docker image prune -f
